# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/EGG
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - restore_cache:
          key: v2.16-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools
            pip install -r requirements.txt
            pip install tox
            pip install black==24.2.0
            pip install isort
            pip install flake8
            pip install requests

      - save_cache:
          paths:
            - ./venv
          key: v2.16-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: black-check
          command: |
            . venv/bin/activate
            tox -e black-check
      - run:
          name: isort-check
          command: |
            . venv/bin/activate
            tox -e isort-check
      - run:
          name: flake8
          command: |
            . venv/bin/activate
            tox -e flake8
      - run:
          name: copyright
          command: |
            . venv/bin/activate
            tox -e check-copyright
      - run:
          name: pytest
          command: |
            . venv/bin/activate
            pytest
